package com.dpas.client;

/* these are generated by the hello-world-server contract */

import com.dpas.DpasServiceGrpc;
import io.grpc.Channel;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

import java.util.logging.Logger;

public class DpasClient {
    private static final Logger logger = Logger.getLogger(DpasClient.class.getName());
    private final DpasServiceGrpc.DpasServiceBlockingStub blockingStub;

    public DpasClient(Channel channel) {
        blockingStub = DpasServiceGrpc.newBlockingStub(channel);
    }

    public static void main(String[] args) throws Exception {

        if (args.length < 2) {
            System.err.println("Argument(s) missing!");
            System.err.printf("Usage: java %s host port%n", DpasClient.class.getName());
            return;
        }

        final String host = args[0];
        final int port = Integer.parseInt(args[1]);
        final String target = host + ":" + port;


        final ManagedChannel channel = ManagedChannelBuilder.forTarget(target).usePlaintext().build();

        DpasServiceGrpc.DpasServiceBlockingStub stub = DpasServiceGrpc.newBlockingStub(channel);

        ClientAPI library = ClientAPI.getInstance();
        String input = "register|user1\nregister|user2\npost|user1|ola isto e um teste\nread|user2|user1|0\npostGeneral|user1|teste do geral|1\nreadGeneral|user2|0";
        //read->user that wants to read|user particular board wanted; readGeneral->user that wants to read
        String[] commands = input.split("\n");
        for (String command : commands) {
            library.receive(stub, command);
        }
        channel.shutdownNow();
    }

}
